import { defaultSpeechVoice, isTextToSpeechConfigured } from "../../../ai/speech"
import type { SpeechAudioFormat } from "../../../ai/speech"
import { isAppError } from "../../../shared/errors"
import { attachmentService } from "../../attachment/attachment.service"
import { speechService } from "../../speech/speech.service"
import { renderSynthesis, speechSynthesizeParameters } from "./speech-content"
import type { AgentTool, ToolContext, ToolResult } from "./types"

/**
 * MP3 and only MP3, rather than exposing the format union to the model.
 *
 * The generated bytes go back through the ordinary upload path, which decides
 * what a file is from its own signature — and `pcm` is raw samples with no
 * header at all, so it has no signature to decide from and would be refused as
 * "not a recording it can read". MP3 sniffs cleanly, plays everywhere and is
 * compressed, which is what a stored artefact should be. A model choosing a
 * container is a choice with no upside and one failure mode.
 */
const SYNTHESIS_FORMAT: SpeechAudioFormat = "mp3"

/**
 * Speak a piece of text, and hand back the recording as an attachment.
 *
 * The interesting decision is that this returns an **id, not audio**. A tool
 * result is text the model reads, and audio is not text: inlining a base64 MP3
 * would fill the run's context with something it cannot listen to and charge it
 * by the token for the privilege. So the recording is stored as an unbound
 * `message_attachment` — exactly the state an attachment is in between upload
 * and the message that claims it (ADR-037) — and the id is what comes back. That
 * is what makes "agent → speech → an audio output" a workflow step: the next
 * step, a chat message or a Phase 4 workflow output takes the id and delivers
 * the file.
 *
 * `writes: false` although it inserts a row. The approval gate keys on *leaving*
 * Ragenta — sending mail, POSTing into a customer's system — because those get
 * it wrong once and it has happened (ADR-032). This writes an object into
 * Ragenta's own bucket that nothing points at until somebody chooses to; getting
 * it wrong costs some credits and leaves an orphan, which is the same shape of
 * mistake as an unnecessary OCR. Making it `true` would put an approval prompt
 * in front of every read-aloud step and teach people to click through them.
 */
export const speechSynthesizeTool: AgentTool = {
	name: "speech_synthesize",
	description:
		"Speak text aloud and save it as an audio attachment. It returns the new attachment's id, not the audio itself — pass that id on to whatever should play, send or store the recording. Use it when the answer should be heard rather than read.",
	parameters: speechSynthesizeParameters,
	writes: false,

	async execute(context: ToolContext, args: unknown): Promise<ToolResult> {
		const input = speechSynthesizeParameters.parse(args)

		if (!(await isTextToSpeechConfigured())) {
			return {
				ok: false,
				content:
					"This deployment has no text-to-speech configured, so it cannot generate speech.",
				metadata: { refused: "tts_not_configured" },
			}
		}

		try {
			const spoken = await speechService.synthesize(
				// The run's workspace, never anything the model supplied — it is what
				// scopes the credit check, the charge and the row written below
				// (`.claude/rules/security.md`).
				context.workspaceId,
				{ text: input.text, voice: input.voice, format: SYNTHESIS_FORMAT },
				context.userId,
				// Deliberately no caller-supplied reference: every attempt that reaches
				// this line has made, or is about to make, a real billable call to the
				// provider, so every attempt is a real charge. A retry only happens
				// because the node failed, and re-running it synthesises the audio
				// again — deduplicating those would bill one call and make two.
				//
				// `context.stepSeq` in particular must NOT be used here. It is not
				// unique within a run: `runToolNode` passes 0 for every graph tool node
				// and `runToolLoop` restarts it per invocation, so a flow with a `tts`
				// node inside a loop would collide on one reference and be charged once
				// for twenty-five syntheses.
			)

			const attachment = await attachmentService.upload(
				context.workspaceId,
				{
					// Display only; the storage key is generated from the row's id. The
					// run and step make it recognisable on a timeline that may hold
					// several.
					name: `speech-${context.runId}-${context.stepSeq}.mp3`,
					declaredMimeType: spoken.mimeType,
					bytes: spoken.audio,
				},
				context.userId,
			)

			return {
				ok: true,
				content: renderSynthesis({
					attachmentId: attachment.id,
					mimeType: attachment.mimeType,
					sizeBytes: attachment.sizeBytes,
					characters: input.text.length,
				}),
				metadata: {
					attachmentId: attachment.id,
					mimeType: attachment.mimeType,
					sizeBytes: attachment.sizeBytes,
					characters: input.text.length,
					voice: input.voice ?? (await defaultSpeechVoice()) ?? null,
					// Null, and stays null: nothing decodes the container to measure it,
					// and a guessed duration would be a wrong number on the timeline
					// (`attachment/validate.ts`).
					durationMs: attachment.durationMs,
				},
			}
		} catch (error) {
			// No configured voice, a workspace out of credits, a provider that
			// refused, or storage that would not take the object — a refusal rather
			// than a throw, so the run can answer in text instead (`types.ts`).
			return {
				ok: false,
				content: isAppError(error) ? error.message : "That text could not be spoken.",
				metadata: {
					characters: input.text.length,
					refused: isAppError(error) ? error.code : "synthesize_failed",
				},
			}
		}
	},
}
